# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: windows-2019

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run cypress:verify
  displayName: 'Cypress Verify'

- script: |
    npm run cypress:run:reporter
  displayName: 'Run cypress tests'

- script: |
      cd Users-luma.guimaraes-Desktop-Solutis-TesteAzureLocal-TesteAzure && npm run cypress
  displayName: 'npm cypress run'
- script: |
      cd bff-ura-midway && npm run cypress:verify
  displayName: 'Verify if Cypress can be executed'
- script: |
      cd bff-ura-midway && npm run cypress:run
  displayName: 'Executed test Cypress'

- task: PublishTestResults@2
  displayName: 'Publish the test reports'
  inputs:
    testResultsFiles: '**/test-*.xml'
  condition: succeededOrFailed()
  continueOnError: true